config/routes.rb
Rails.application.routes.draw do
  resources :lessons
  resources :sections do
    resources :lessons
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/section.rb
class Section < ActiveRecord::Base
  has_many :lessons
  validates :name, :presence => true
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :section

  validates :name, :presence => true
  validates :content, :presence => true

  scope(:not_learned, -> do
    where({:learned => false})
  end)

  # scope :search, -> (name) { where("name like ?", "%#{name}%")}

  def self.search(term)
    if term
      where("content Like ?", "%#{term}%").order('number')
    else
      order('number')
    end
  end

  def self.not_learned
    where(learned: false)
  end

  define_method(:next) do
    next_lesson = nil
    lessons = Lesson.all.order(:number)
    lessons.each() do |lesson|
      if lesson.number > self.number
        next_lesson = lesson
        break
      else
        next_lesson = self
      end
    end
    next_lesson
  end

  define_method(:previous) do
    previous_lesson = nil
    lessons = Lesson.all.order(number: :desc)
    lessons.each() do |lesson|
      if lesson.number < self.number
        previous_lesson = lesson
        break
      else
        previous_lesson = self
      end
    end
    previous_lesson
  end
end

app/models/section.rb
class Section < ActiveRecord::Base
  has_many :lessons
  validates :name, :presence => true

  def self.search(term)
    if term
      where('name LIKE ?', "%#{term}%")
    else
      all
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def index
    @lessons = Lesson.search(params[:term])
    render :index
  end

  def show
    @lesson = Lesson.find(params[:id])
    @next_lesson = @lesson.next
    @previous_lesson = @lesson.previous
    render :show
  end

  def new
    @section = Section.find(params[:section_id])
    @lesson = @section.lessons.new
    render :new
  end

  def create
    @section = Section.find(params[:section_id])
    @lesson = @section.lessons.new(lesson_params)
    if @lesson.save
      redirect_to  section_path(@section)
    else
      render :new
    end
  end

  def edit
    @section = Section.find(params[:section_id])
    @lesson = Lesson.find(params[:id])
    render :edit
  end

  def update
    @section = Section.find(params[:section_id])
    @lesson = Lesson.find(params[:id])
      if @lesson.update(lesson_params)
        redirect_to section_path(@section)
      else
        render :edit
      end
  end

  def destroy
    @section = Section.find(params[:section_id])
    @lesson = Lesson.find(params[:id])
    @lesson.destroy
    redirect_to section_path(@section)
  end

  private
    def lesson_params
      params.require(:lesson).permit(:name, :content, :number, :term)
    end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  def index
    @sections = Section.search(params[:term])
    render :index
  end

  def show
    @section = Section.find(params[:id])
    render :show
  end

  def new
    @section = Section.new
    render :new
  end

  def create
    @section = Section.new(section_params)
    if @section.save
      redirect_to sections_path
    else
      render :new
    end
  end

  def edit
    @section = Section.find(params[:id])
    render :edit
  end

  def update
    @section = Section.find(params[:id])
      if @section.update(section_params)
        redirect_to sections_path
      else
        render :edit
      end
  end

  def destroy
    @section = Section.find(params[:id])
    @section.destroy
    redirect_to sections_path
  end

  private
    def section_params
      params.require(:section).permit(:name, :species)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LearnHowToProgram</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/lessons/_form.html.erb
<%= render "layouts/errors", :object => @lesson %>

<%= form_for [@section, @lesson] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :content %>
  <%= f.text_area :content %>
  <%= f.label :number %>
  <%= f.number_field :number %>
  <%= f.submit %>
<% end %>

app/views/lessons/edit.html.erb
<h1>Edit lesson</h1>

<%= render "form" %>

app/views/lessons/index.html.erb
<%= form_tag(lessons_path, method: :get) do %>
  <%= text_field_tag :term, params[:term] %>
  <%= submit_tag 'Search', name: nil %>
<% end %>
<h1>Lessons</h1>

<ul>
  <% @lessons.each do |lesson| %>
    <li><%= lesson.number %> <%= link_to lesson.name, lesson_path(lesson) %></li>
  <% end %>
</ul>
<hr>
<%= link_to "New Lesson", new_lesson_path %>

app/views/lessons/new.html.erb
<h1>New lesson for <%= @section.name %></h1>

<%= render "form" %>

app/views/lessons/show.html.erb
<nav class="navbar">
  <span><%= link_to "Previous", lesson_path(@previous_lesson) %></span>
  <span><%= link_to "Next", lesson_path(@next_lesson) %></span>
</nav>
<% content_for(:top, "Lesson | Learn how to Program") %>

<h1><%= @lesson.number %>. <%= @lesson.name %></h1>
<p><%= @lesson.content %></p>

<p><%= link_to "Edit", edit_lesson_path(@lesson) %></p>
<p><%= link_to "Delete Lesson", lesson_path(@lesson),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>

<p><%= link_to "Return to lessons", lessons_path %></p>

app/views/sections/_form.html.erb
<%= render "layouts/errors", :object => @section %>

<%= form_for [@section] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/sections/index.html.erb
<nav>
  <%= form_tag(sections_path, method: :get) do %>
    <%= text_field_tag :term %>
    <%= submit_tag 'Search' %>
  <% end %>
</nav>
<h1>Sections</h1>

<ul>
  <% @sections.each do |section| %>
    <li><%= link_to section.name, section_path(section) %></li>
  <% end %>
</ul>
<hr>
<%= link_to "New Section", new_section_path %>

app/views/sections/new.html.erb
<%= render "form" %>

app/views/sections/show.html.erb
<h1><%= @section.name %></h1>

<% if @section.lessons.any? %>
  <h4>Here are the lessons for this section:</h4>

  <ul>
    <% @section.lessons.each do |lesson| %>
      <li>
        <%= lesson.name %> |
        <%= link_to "Edit", edit_section_lesson_path(@section, lesson) %> |
        <%= link_to "Delete", section_lesson_path(@section, lesson),
                                 :data => {:confirm => "Are you sure?",
                                                :method => "delete"} %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>There are no lessons yet!</p>
<% end %>

<p><%= link_to "Add a lesson", new_section_lesson_path(@section) %></p>